version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_14Sep
  packages:
  - name: EdgeSIQA14Sep
    version: "1.0"
- serviceName: edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_14Sep2
  packages:
  - name: EdgeSIQA14Sep
    version: "1.0"
configurationVariables:
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.trustStore
  : ""
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.poolable
  : "false"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.portNumber
  : "1433"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.serverName
  : vmiboint01
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.keyStore
  : ""
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.dbType
  : MSSQL
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.keyStore
  : ""
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.portNumber
  : "1433"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.user
  : sa
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.trustStore
  : ""
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.poolable
  : "false"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.dbType
  : MSSQL
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionEnabled
  : "false"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.networkProtocol
  : tcp
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionEnabled
  : "false"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.networkProtocol
  : tcp
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionSettings.user
  : sa
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.EdgeSIQA14Sep.edge.siqa14sep.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_14Sep2.connectionSettings.serverName
  : vmiboint01
packages:
- name: EdgeSIQA14Sep
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag/EdgeSIQA14Sep
  gitUsername: prabhakarsag
  gitToken: edge.scaffolding.EdgeSIQA14Sep.SIQAPsurGit.gitToken
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
  wpmToken: edge.scaffolding.WmJDBCAdapter.https://packages.softwareag.com.wpmToken
